### ISSUE TITLE
Add border and background properties for easier styling

### ISSUE THREAD

**Issue by bdenham** [HiDeoo/starlight-sidebar-topics#24]
### Is your feature request related to a problem?

I would like to easily immulate the sidebar look and feel of Astro Docs.

<img width="288" alt="Image" src="https://github.com/user-attachments/assets/4d3cd4f7-8349-4710-9b04-af3cce044eee" />

### Describe the solution you'd like

Add extensible styling properties to make this easy.

### Describe alternatives you've considered

I'm currently overriding existing classes using `.sidebar-content > ul` and associated variables like `--sl-sidebar-item-padding-inline`.

### Additional Context

Or create themes that can be overridden, including icon sizes (to make them smaller).

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands:

I'm a bit hesitant to add right now custom variables to style the topics list as I'm still not 100% happy with the default look and plan on iterating on it so I think it's better to wait before providing them.

The idea of custom themes is also interesting, keeping that in mind to think about it.

For the moment, I just pushed a new version adding the `.starlight-sidebar-topics` CSS class around the topics list to make it easier to target it.

For example, using this new class, trying to make it looks like Astro Docs would looks something like this using [Starlight custom CSS](https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles):

```css
.starlight-sidebar-topics {
  --topic-background-color-current: var(--sl-color-black);
  --topic-border-radius: 0.5rem;

  --topics-background-color: var(--sl-color-gray-7, var(--sl-color-gray-6));
  --topics-border-width: 1px;
  --topics-padding: calc(0.25rem - var(--topics-border-width));
  --topics-border-radius: calc(var(--topic-border-radius) + var(--topics-padding) + var(--topics-border-width));

  background-color: var(--topics-background-color);
  border: var(--topics-border-width) solid var(--sl-color-hairline-light);
  border-radius: var(--topics-border-radius);
  padding: var(--topics-padding);
}

.starlight-sidebar-topics::after {
  display: none;
}

.starlight-sidebar-topics a {
  border: 1px solid transparent;
  border-radius: var(--topic-border-radius);
  color: var(--sl-color-gray-2);
  padding: calc(0.5rem - var(--topics-border-width));
}

.starlight-sidebar-topics a:is(:hover, :focus-visible) {
  background-color: var(--topic-background-color-current);
  color: var(--sl-color-white);
}

.starlight-sidebar-topics a.starlight-sidebar-topics-current {
  background-color: var(--topic-background-color-current);
  border-color: var(--sl-color-hairline-light);
  color: var(--sl-color-white);
}

.starlight-sidebar-topics .starlight-sidebar-topics-icon {
  border: none;
}

.starlight-sidebar-topics a .starlight-sidebar-topics-icon {
  background-color: inherit;
  color: var(--sl-color-gray-3);
}

.starlight-sidebar-topics
  a:not(.starlight-sidebar-topics-current):is(:hover, :focus-visible)
  .starlight-sidebar-topics-icon {
  color: inherit;
}

.starlight-sidebar-topics a.starlight-sidebar-topics-current .starlight-sidebar-topics-icon {
  color: var(--sl-color-text-accent);
}

@media (min-width: 50rem) {
  .starlight-sidebar-topics {
    --topic-background-color-current: var(--sl-color-gray-6);
    --topics-background-color: var(--sl-color-black);
  }
}
```

<img width="292" alt="Image" src="https://github.com/user-attachments/assets/af8f90ea-bbd8-41ca-98c6-5e766bd653ef" />

Not that it's basic CSS I wrote quickly and probably need some tweaking to look exactly like Astro Docs but it should give a good starting point.
